words = [
    {"hungarian": "alvás", "english": "sleep"},
    {"hungarian": "ébredés", "english": "wake up"},
    {"hungarian": "mosakodás", "english": "wash"},
    {"hungarian": "öltözködés", "english": "dress"},
    {"hungarian": "gyors", "english": "fast"},
    {"hungarian": "lassú", "english": "slow"},
    {"hungarian": "hideg", "english": "cold"},
    {"hungarian": "meleg", "english": "warm"},
    {"hungarian": "nyár", "english": "summer"},
    {"hungarian": "tél", "english": "winter"},
    {"hungarian": "ősz", "english": "autumn"},
    {"hungarian": "tavasz", "english": "spring"},
    {"hungarian": "születésnap", "english": "birthday"},
    {"hungarian": "boldog", "english": "happy"},
    {"hungarian": "szomorú", "english": "sad"},
    {"hungarian": "fáradt", "english": "tired"},
    {"hungarian": "pihen", "english": "rest"},
    {"hungarian": "munka", "english": "work"},
    {"hungarian": "játék", "english": "game"},
    {"hungarian": "mozifilm", "english": "movie"},
    {"hungarian": "könyv", "english": "book"},
    {"hungarian": "zenekar", "english": "band"},
    {"hungarian": "újság", "english": "newspaper"},
    {"hungarian": "város", "english": "city"},
    {"hungarian": "ország", "english": "country"}
]